# Generated by Django 2.1.7 on 2019-04-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='bandwidth_usage',
        ),
        migrations.AddField(
            model_name='battery',
            name='i_in',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='battery',
            name='i_out',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='battery',
            name='temp',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battery',
            name='v_in',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='battery',
            name='v_out',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='battery',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='battery',
            name='timestamp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='router',
            name='timestamp',
            field=models.PositiveIntegerField(),
        ),
    ]
