# Generated by Django 2.1.7 on 2019-04-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190408_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battery',
            old_name='status',
            new_name='is_charging',
        ),
        migrations.RenameField(
            model_name='router',
            old_name='status',
            new_name='isConnected',
        ),
    ]
