# Generated by Django 2.1.7 on 2019-04-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190408_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='router',
            old_name='isConnected',
            new_name='is_connected',
        ),
    ]
