# Generated by Django 2.1.7 on 2019-04-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190408_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='battery',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
