# Generated by Django 2.1.7 on 2019-04-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190408_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='locker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lockers', models.PositiveSmallIntegerField(default=0)),
                ('num_charging', models.PositiveSmallIntegerField(default=0)),
                ('num_charged', models.PositiveSmallIntegerField(default=0)),
                ('energy_used', models.FloatField(default=0)),
                ('web_interface', models.TextField(default='./')),
                ('timestamp', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Modem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_connected', models.BooleanField(default=False)),
                ('is_on', models.BooleanField(default=False)),
                ('bandwidth', models.PositiveIntegerField(default=0)),
                ('bandwidth_usage', models.PositiveIntegerField(default=0)),
                ('web_interface', models.TextField()),
                ('timestamp', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='battery',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='router',
            name='is_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='router',
            name='num_device',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='router',
            name='web_interface',
            field=models.TextField(default='./'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='is_charging',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='router',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='router',
            name='timestamp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
