# Generated by Django 2.2 on 2019-04-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190418_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
