# Generated by Django 2.2 on 2019-04-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190419_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kiosk',
        ),
        migrations.AddField(
            model_name='amenities',
            name='kiosk_temp',
            field=models.FloatField(default=0),
        ),
    ]
