# Generated by Django 2.2 on 2019-04-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190419_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='timestamp',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
