# Generated by Django 2.2 on 2019-04-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_amenities_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battery',
            old_name='i_in',
            new_name='e_in',
        ),
        migrations.RenameField(
            model_name='battery',
            old_name='i_out',
            new_name='e_out',
        ),
        migrations.RenameField(
            model_name='battery',
            old_name='v_in',
            new_name='p_in',
        ),
        migrations.RenameField(
            model_name='battery',
            old_name='v_out',
            new_name='p_out',
        ),
    ]
