# Generated by Django 2.2 on 2019-04-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190419_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_connected', models.BooleanField(default=False)),
                ('is_modem_on', models.BooleanField(default=False)),
                ('bandwidth', models.PositiveIntegerField(default=0)),
                ('bandwidth_usage', models.PositiveIntegerField(default=0)),
                ('modem_web_interface', models.TextField()),
                ('timestamp', models.PositiveIntegerField(default=0)),
                ('is_router_on', models.BooleanField(default=False)),
                ('num_device', models.PositiveSmallIntegerField(default=0)),
                ('router_web_interface', models.TextField(default='./')),
            ],
        ),
        migrations.DeleteModel(
            name='Modem',
        ),
        migrations.DeleteModel(
            name='router',
        ),
    ]
