# Generated by Django 2.2 on 2019-04-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190422_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='timestamp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
