# Generated by Django 2.2 on 2019-04-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190422_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='locker',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
