# Generated by Django 2.2 on 2019-04-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190422_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='blender_p',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='coffee_machine_p',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='kiosk_lights_p',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='kiosk_temp',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='locker_lights_p',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='mini_fridge_p',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='tv_p',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battery',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battery',
            name='e_in',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battery',
            name='e_out',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battery',
            name='p_in',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battery',
            name='p_out',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battery',
            name='percentage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locker',
            name='energy_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
